// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYWgC6Ra_2hO3X3NbuIAeC8Z4HB2r55kw',
    appId: '1:792943513733:web:9849dd10e2c18bb99b19ec',
    messagingSenderId: '792943513733',
    projectId: 'cmsc-23-project-group-2',
    authDomain: 'cmsc-23-project-group-2.firebaseapp.com',
    storageBucket: 'cmsc-23-project-group-2.appspot.com',
    measurementId: 'G-WT0HPLR0BB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHmh66XU3obxbi6c-ME2COKpXSezDgyMs',
    appId: '1:792943513733:android:5fae1321e6c784e29b19ec',
    messagingSenderId: '792943513733',
    projectId: 'cmsc-23-project-group-2',
    storageBucket: 'cmsc-23-project-group-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSuchJEfigBno87GymUv2-4KYfP0NRbrc',
    appId: '1:792943513733:ios:c0db0d6ab33b0e169b19ec',
    messagingSenderId: '792943513733',
    projectId: 'cmsc-23-project-group-2',
    storageBucket: 'cmsc-23-project-group-2.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSuchJEfigBno87GymUv2-4KYfP0NRbrc',
    appId: '1:792943513733:ios:c0db0d6ab33b0e169b19ec',
    messagingSenderId: '792943513733',
    projectId: 'cmsc-23-project-group-2',
    storageBucket: 'cmsc-23-project-group-2.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYWgC6Ra_2hO3X3NbuIAeC8Z4HB2r55kw',
    appId: '1:792943513733:web:cc9919fe520f60539b19ec',
    messagingSenderId: '792943513733',
    projectId: 'cmsc-23-project-group-2',
    authDomain: 'cmsc-23-project-group-2.firebaseapp.com',
    storageBucket: 'cmsc-23-project-group-2.appspot.com',
    measurementId: 'G-ZFBKK5ZYBV',
  );
}
